
- platform: command_line
  switches:
    mote_light_4_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/on_animated_4_mote/colour/ee7000
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/off_animated_4_mote
      command_state: python3 /path/to/file/mote-on-off-state.py | grep 'on'
      friendly_name: Mote Toggle 4-Mote


- platform: command_line
  switches:
    mote_swipe_in_4_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/swipe_in_4_mote/colour/ee7000
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/swipe_out_4_mote/colour/000000
      friendly_name: Mote Swipe In 4-Mote


- platform: command_line
  switches:
    mote_swipe_out_4_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/swipe_out_4_mote/colour/ee7000
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/swipe_in_4_mote/colour/000000
      friendly_name: Mote Swipe Out 4-Mote


- platform: command_line
  switches:
    mote_cylon_uno_4_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/cylon_uno_4_mote/colour/ff0000
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/swipe_out_4_mote/colour/ee7000
      friendly_name: Mote Cylon Uno 4-Mote


- platform: command_line
  switches:
    mote_cylon_duo_4_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/cylon_duo_4_mote/colour/ff0000
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/swipe_out_4_mote/colour/ee7000
      friendly_name: Mote Cylon Duo 4-Mote


- platform: command_line
  switches:
    mote_rainbow_4_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/rainbow
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/on_animated_4_mote/colour/ee7000
      friendly_name: Mote Rainbow 4-Mote


- platform: command_line
  switches:
    mote_tie_dye_4_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/tiedye
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]:5000/mote/api/v1.0/on_animated_4_mote/colour/ee7000
      friendly_name: Mote Tie Dye 4-Mote
