## Mote Light Switch Board
- platform: command_line
  switches:
    mote_light_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/on_animated_2_mote/colour/ee7000/1/2
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/off_animated_2_mote/1/2
      command_state: python3 /path/to/file/mote-on-off-state.py | grep 'on'
      friendly_name: Mote Toggle 2-Mote


- platform: command_line
  switches:
    mote_swipe_over_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_over_2_mote/colour/ee7000/1/2
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_out_2_mote/colour/000000/1/2
      friendly_name: Mote Swipe Over 2-Mote


- platform: command_line
  switches:
    mote_swipe_back_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_out_2_mote/colour/ee7000/1/2
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_over_2_mote/colour/000000/1/2
      friendly_name: Mote Swipe Back 2-Mote


- platform: command_line
  switches:
    mote_swipe_in_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_in_2_mote/colour/ee7000/1/2
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_out_2_mote/colour/000000/1/2
      friendly_name: Mote Swipe In 2-Mote


- platform: command_line
  switches:
    mote_swipe_out_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_out_2_mote/colour/ee7000/1/2
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_in_2_mote/colour/000000/1/2
      friendly_name: Mote Swipe Out 2-Mote


- platform: command_line
  switches:
    mote_cylon_uno_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/cylon_uno_2_mote/colour/ff0000/1/2
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_out_2_mote/colour/ee7000/1/2
      friendly_name: Mote Cylon Uno 2-Mote


- platform: command_line
  switches:
    mote_cylon_duo_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/cylon_duo_2_mote/colour/ff0000/1/2
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/swipe_out_2_mote/colour/ee7000/1/2
      friendly_name: Mote Cylon Duo 2-Mote


- platform: command_line
  switches:
    mote_rainbow_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/rainbow
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/on_animated_2_mote/colour/ee7000/1/2
      friendly_name: Mote Rainbow 2-Mote


- platform: command_line
  switches:
    mote_tie_dye_2_mote:
      command_on: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/tiedye
      command_off: curl -s http://[ Rasp_Pi_IP:5000 ]/mote/api/v1.0/on_animated_2_mote/colour/ee7000/1/2
      friendly_name: Mote Tie Dye 2-Mote
